[package]
name = "h-exprs"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7"
pest_derive = "2.1"
clap = "4.0"
open-hypergraphs = "0.2.3"
open-hypergraphs-dot = "0.2.1"
graphviz-rust = "0.9.5"
